class Main$BadLuckException extends java.lang.Exception
{

    void <init>(java.lang.String)
    {
        Main$BadLuckException r0;
        java.lang.String r1;

        r0 := @this: Main$BadLuckException;

        r1 := @parameter0: java.lang.String;

        specialinvoke r0.<java.lang.Exception: void <init>(java.lang.String)>(r1);

        return;
    }

    void <init>(java.lang.Throwable)
    {
        java.lang.Throwable r1;
        Main$BadLuckException r0;

        r0 := @this: Main$BadLuckException;

        r1 := @parameter0: java.lang.Throwable;

        specialinvoke r0.<java.lang.Exception: void <init>(java.lang.Throwable)>(r1);

        return;
    }

    void <init>(java.lang.String, java.lang.Throwable)
    {
        java.lang.Throwable r2;
        Main$BadLuckException r0;
        java.lang.String r1;

        r0 := @this: Main$BadLuckException;

        r1 := @parameter0: java.lang.String;

        r2 := @parameter1: java.lang.Throwable;

        specialinvoke r0.<java.lang.Exception: void <init>(java.lang.String,java.lang.Throwable)>(r1, r2);

        return;
    }

    void <init>(java.lang.Throwable, java.lang.String)
    {
        java.lang.Throwable r2;
        Main$BadLuckException r0;
        java.lang.String r1;

        r0 := @this: Main$BadLuckException;

        r2 := @parameter0: java.lang.Throwable;

        r1 := @parameter1: java.lang.String;

        specialinvoke r0.<java.lang.Exception: void <init>(java.lang.String,java.lang.Throwable)>(r1, r2);

        return;
    }
}
